/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ancla;

import com.ancla.builder.Book;
import com.ancla.builder.FacadeBuilder;
import com.ancla.enums.Genre;

public class Patterns {
  public static void main(String[] args) {
    callBookBuilder();
    callFacadeBuilder();
  }

  private static void callBookBuilder() {
    var builder = new Book.BookBuilder("123", "Title");
    builder.addAuthor("Andru").addDesc("Some Description").addGender(Genre.HISTORY);
    System.out.println(builder.build());
  }

  private static void callFacadeBuilder() {
    FacadeBuilder fb = new FacadeBuilder();

    fb.lives()
        .at("St 27")
        .in("NY")
        .withPostCode("123")
        .works()
        .company("Foo")
        .position("Developer")
        .income(12345678);

    System.out.println(fb.build());
  }
}
