/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ancla;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

import java.time.Year;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import com.ancla.builder.Book;
import com.ancla.enums.Genre;

class BookBuilderTest {
  @Test
  @DisplayName("Testing Book builder")
  void testingBookBuilder() {
    var bookObject = new Book.BookBuilder("123456", "Title");
    bookObject.addGender(Genre.FANTASY).addPublished(Year.now());

    Book book = bookObject.build();

    assertEquals("123456", book.getIsbn());
    assertEquals("Title", book.getTitle());
    assertEquals(Genre.FANTASY, book.getGenre());
    assertEquals(Year.now(), book.getPublished());
    assertNull(book.getDescription());
  }
}
